language: node_js
node_js:
- 'node'
install:
- npm install
- npm install jsonlint
script:
- npm run test
- npm run build
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/push.sh; fi'
env:
  global:
    secure: "MK+6nPyvb9ylbE7TQ5wLOZf+X4cOCSM23PMaWjFJ9SMeOlB7SSJy9s2Wp0tE+6+832QCP/NBz857FpMSRV3mxTTtUpeY93RuxSGpTQziGRATkQ6rvRlJCjeIU3INMGEX1kh8fKSq61nDPBHMW9aaGMIFQhntkaQRb3skjG84EFMvmSD0iSvq6CKTNYBdXFOiaVAChblNpqzpeZKIt9p2ywjIHcCeQKenQkAcRFySybPjE4QWRuWA0nwDDvqbr/qJ8Bnob+wBuj3wsSRN1kioQNgewjYGR1ZIBHgZ8enXn91b+fnq2e6fC+d/Dw6oE3bn1izPoRL+4kLT9PO+GsXjgwZ8piEjrnVzTGKQEi7U7T5dq/6xx/yzMt8Ga1JJKm956mqLaip+4lL/ScLX1uYSpkc3HM0ILT6HSr+fPgcVk+aVJdz4uZui5/U4WHe7+1EfC+edor3Nyl+bpa5XM5fnyCRvY2A+fsSZhBzx/PEMkj5kb6x9B0ybs6EViamDktSbCAKwdwU9LEGr/G+cimrXiZvNVi7tFNdbi5/7opTmLlQN8nUjSlFS/270yfe2Qd4EV/GEyVTO2EkZrMQ1fumoJWL3cQ2eaOF/7RwCnweshRV13ZUc4Mtnz38YLchVZPkfHq/xJtfBK6csmS7OzjBJ1OOe+GkYLz0yZ63clDckk54="